---
- name: Generate Report
  hosts: localhost
  gather_facts: false
  vars_files:
    - ../secrets/proxmox/api
    - ../secrets/discord/webhook
  tasks:
    - name: pull proxmox facts
      community.proxmox.proxmox_vm_info:
        api_host: "{{ proxmox_api_host | default(omit) }}"
        api_port: "{{ proxmox_api_port | default(omit) }}"
        api_user: "{{ proxmox_api_user | default(omit) }}"
        api_password: "{{ proxmox_api_pass | default(omit) }}"
        api_token_id: "{{ proxmox_token_id | default(omit) }}"
        api_token_secret: "{{ proxmox_api_key | default(omit) }}"
      register: vm_info

    - name: Send vm info to the Discord channel
      community.general.discord:
        webhook_id: "{{ discord_webhook_id }}"
        webhook_token: "{{ discord_webhook_token }}"
        content: "{{ lookup('template', '../templates/discord_vm_report.j2', template_vars={'vms': item}) }}"
      loop: "{{ vm_info.proxmox_vms | batch(5) | list }}"
